### ISSUE TITLE
Icons missing in the dropdown

### ISSUE THREAD

**Issue by ikornaselur** [koddsson/github-emojis-chrome#3]
### Steps to reproduce
1. Find a input box on a github issue
2. Type "$"
### Expected result

A dropdown list with emojis with corresponding icons
### Actual result

A list of emojis but corresponding icons are missing. The following screenshot shows the issue:  

![2015-01-05-150127_169x332_scrot](https://cloud.githubusercontent.com/assets/3537289/5614800/9dfe2874-94ec-11e4-93c1-a743ffe2a7dc.png)
### Other

OS: Ubuntu 12.04 LTS
Browser Version: 38.0.2125.104

**Comment by koddsson** [comment]
Thank you for this, I'll hopefully be able to check it out this week. :smile:

**Comment by koddsson** [comment]
This took longer than expected and turned out to be a deployment issue! Version 0.5 has been released and should fix this. Feel free to re-open if the problem persists with version 0.5.

(and remind me to buy you the equivalent of a cupcake for filing this issue! (since I know you don't eat cupcakes!!))

**Comment by ikornaselur** [comment]
Confirmed to be fixed on my side! :tropical_fish:

**Comment by koddsson** [comment]
:snowman:
